#!/bin/sh -e

export APP_ENV="local"
if [ "$TRAVIS" == "true" ]; then
    export APP_ENV="test"
fi

echo "==> Building docker image..."
docker build . --rm -t "wordcounter" --build-arg APP_ENV=$APP_ENV
